### ISSUE TITLE
Not working after Production Deployement 

### ISSUE THREAD

**Issue by harivyas35** [edumeet/edumeet#485]
Hi,
I have deployed the app using Amazon EC2 service
using nginx for reverse proxy.
The server is running fantastically , but when enter the URL to connect ,it connects to the app and below page is shown which says :
Required functionality not availble in your browser
This meeting service requires functionality not supported by your browser. Please upgrade, switch to a different browser, or check your settings. Supported browsers etc .But the browser that i am using is upto date (Chromium 77+ ,chrome 77+,and firefor latest).

My nginx file has below configuration.

server {
  listen 80 default_server;
  server_name _;

 
  location / {
    proxy_pass https://13.127.210.196:8000;
  }
}

13.127.210.196 is my private ip address.
also below are my changes for config.js files

in app/public/config/config.js file 

developmentPort : 8000,
productionPort  : 8000,

And the changes in server/congig/config.js are as follows
listeningPort         : 8000,
listeningRedirectPort : 8080,
In  mediasoup WebRtcTransport setting 
I have put the ip as 13.127.210.196
and 
 fileTracker  : 'wss://tracker.lab.vvc.niif.hu:8000',
TURN server , i have kept the port as 8000.
and I have generated cert.pem and key.pem and used them
I am not able to figure out what i am missing 
I request you to please help me with this issue,as i am trying so hard to deploy it to production.

Regards,
Hari Vyas

**Comment by havfo** [comment]
Have you set `supportedBrowsers` correctly in app config? Take a look in app example config.

**Comment by misi** [comment]
If you proxy communication then check if config trust proxy config is set properly in server config
See: https://expressjs.com/en/guide/behind-proxies.html

**Comment by sraza295** [comment]
Same issue happening with me.
I have deployed in server.
When i am running in app folder by this command:- npm start.
Then project started with https://localhost:4443.

**Comment by misi** [comment]
You should
1. run in app folder 
`npm run build`
2. run in server folder
`npm run start`

**Comment by sraza295** [comment]
@misi 
can i change the url https://localhost:4443/ at the time of development run?
From where we can change the url?

**Comment by havfo** [comment]
You chose the port you want the server to run on in the server config.

**Comment by harivyas35** [comment]
My problem is solved

**Comment by shaikh-kamran** [comment]
@harivyas35 can you explain what exactly you did? as i have a turn server and configured all configuration but still not able to get video and audio
